Traceback (most recent call last):
  File "D:\cedri\anaconda3\envs\prepa\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "D:\cedri\anaconda3\envs\prepa\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "D:\cedri\anaconda3\envs\prepa\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "D:\cedri\anaconda3\envs\prepa\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "D:\cedri\anaconda3\envs\prepa\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "D:\cedri\anaconda3\envs\prepa\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "D:\cedri\anaconda3\envs\prepa\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "D:\cedri\anaconda3\envs\prepa\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%time
"""
Il n'est pas utile de redÃ©finir les incertitudes t1_u1u...
Si vous avez exÃ©cutÃ© le bloc prÃ©cÃ©dent, elles sont en mÃ©moire.
"""



# INITIALISATION
N = 100000  # Nombre de simulations rÃ©alisÃ©es.
c_sim = []  # Liste vide oÃ¹ on va stocker les valeurs

# On simule ici N valeurs d'un seul coup pour chaque mesurandes directs.
# MODIFIER les diffÃ©rentes lignes pour l'adapter aux exemples ici.
t1_sims = t1_m + rd.uniform(-t1_u1u, t1_u1u, N) + rd.uniform(-t1_u2u, t1_u2u, N)
t2_sims = t2_m
d1_sims = d1_m
d2_sims = d2_m 

# MODIFIER la ligne ci aprÃ¨s en utilisant t1_sims, t2_sims... comme si c'Ã©tait de simple flottants.
# Comme ce sont des vecteurs numpy, la vectorialisation appliquera la relation mathÃ©matiques terme Ã  terme : c_sim est un vecteur.
c_sim = 0
print(type(c_sim), c_sim.shape)  # Observer en sortie que c_sim est bien un vecteur de taille N


"""
Estimation de l'incertitude de mesure
"""
c_u = np.std(c_sim, ddof=1)

print("u(c) = " + str(c_u))
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mAttributeError[0m                            Traceback (most recent call last)
Cell [1;32mIn [4], line 23[0m
[0;32m     20[0m [38;5;66;03m# MODIFIER la ligne ci aprÃ¨s en utilisant t1_sims, t2_sims... comme si c'Ã©tait de simple flottants.[39;00m
[0;32m     21[0m [38;5;66;03m# Comme ce sont des vecteurs numpy, la vectorialisation appliquera la relation mathÃ©matiques terme Ã  terme : c_sim est un vecteur.[39;00m
[0;32m     22[0m c_sim [38;5;241m=[39m [38;5;241m0[39m
[1;32m---> 23[0m [38;5;28mprint[39m([38;5;28mtype[39m(c_sim), [43mc_sim[49m[38;5;241;43m.[39;49m[43mshape[49m)  [38;5;66;03m# Observer en sortie que c_sim est bien un vecteur de taille N[39;00m
[0;32m     26[0m [38;5;124;03m"""[39;00m
[0;32m     27[0m [38;5;124;03mEstimation de l'incertitude de mesure[39;00m
[0;32m     28[0m [38;5;124;03m"""[39;00m
[0;32m     29[0m c_u [38;5;241m=[39m np[38;5;241m.[39mstd(c_sim, ddof[38;5;241m=[39m[38;5;241m1[39m)

[1;31mAttributeError[0m: 'int' object has no attribute 'shape'
AttributeError: 'int' object has no attribute 'shape'

