Traceback (most recent call last):
  File "D:\cedri\anaconda3\envs\prepa\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "D:\cedri\anaconda3\envs\prepa\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "D:\cedri\anaconda3\envs\prepa\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "D:\cedri\anaconda3\envs\prepa\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "D:\cedri\anaconda3\envs\prepa\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "D:\cedri\anaconda3\envs\prepa\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "D:\cedri\anaconda3\envs\prepa\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "D:\cedri\anaconda3\envs\prepa\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
f, ax = plt.subplots()
f.suptitle("Carte de controle des mesures")
ax.set_xlabel("Distance (d) (cm)")
ax.set_ylabel("EN")

# capsize sert √† ajouter des barres aux extr√©mit√©s simplement par esth√©tisime.
ax.errorbar(d, c_ms, marker="+", linestyle="", yerr=c_us, capsize=2)  # On ne relit pas les points

print(len([c_mean - c_u] * len(d)))
ax.plot(d, [c_mean] * len(d))  # Trac√© de la moyenne
ax.plot(d, [c_mean - c_u] * len(d), linestyle=":")  # Valeur basse de l'intervalle associ√©e √† l'incertitude sur c_mean
ax.plot(d, [c_mean + c_u] * len(d), linestyle=":")  # Valeur haute de l'intervalle associ√©e √† l'incertitude sur c_mean


plt.show()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mValueError[0m                                Traceback (most recent call last)
Cell [1;32mIn [5], line 7[0m
[0;32m      4[0m ax[38;5;241m.[39mset_ylabel([38;5;124m"[39m[38;5;124mEN[39m[38;5;124m"[39m)
[0;32m      6[0m [38;5;66;03m# capsize sert √† ajouter des barres aux extr√©mit√©s simplement par esth√©tisime.[39;00m
[1;32m----> 7[0m [43max[49m[38;5;241;43m.[39;49m[43merrorbar[49m[43m([49m[43md[49m[43m,[49m[43m [49m[43mc_ms[49m[43m,[49m[43m [49m[43mmarker[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43m+[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mlinestyle[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43myerr[49m[38;5;241;43m=[39;49m[43mc_us[49m[43m,[49m[43m [49m[43mcapsize[49m[38;5;241;43m=[39;49m[38;5;241;43m2[39;49m[43m)[49m  [38;5;66;03m# On ne relit pas les points[39;00m
[0;32m      9[0m [38;5;28mprint[39m([38;5;28mlen[39m([c_mean [38;5;241m-[39m c_u] [38;5;241m*[39m [38;5;28mlen[39m(d)))
[0;32m     10[0m ax[38;5;241m.[39mplot(d, [c_mean] [38;5;241m*[39m [38;5;28mlen[39m(d))  [38;5;66;03m# Trac√© de la moyenne[39;00m

File [1;32mD:\cedri\anaconda3\envs\prepa\lib\site-packages\matplotlib\__init__.py:1423[0m, in [0;36m_preprocess_data.<locals>.inner[1;34m(ax, data, *args, **kwargs)[0m
[0;32m   1420[0m [38;5;129m@functools[39m[38;5;241m.[39mwraps(func)
[0;32m   1421[0m [38;5;28;01mdef[39;00m [38;5;21minner[39m(ax, [38;5;241m*[39margs, data[38;5;241m=[39m[38;5;28;01mNone[39;00m, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[0;32m   1422[0m     [38;5;28;01mif[39;00m data [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m-> 1423[0m         [38;5;28;01mreturn[39;00m func(ax, [38;5;241m*[39m[38;5;28mmap[39m(sanitize_sequence, args), [38;5;241m*[39m[38;5;241m*[39mkwargs)
[0;32m   1425[0m     bound [38;5;241m=[39m new_sig[38;5;241m.[39mbind(ax, [38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[0;32m   1426[0m     auto_label [38;5;241m=[39m (bound[38;5;241m.[39marguments[38;5;241m.[39mget(label_namer)
[0;32m   1427[0m                   [38;5;129;01mor[39;00m bound[38;5;241m.[39mkwargs[38;5;241m.[39mget(label_namer))

File [1;32mD:\cedri\anaconda3\envs\prepa\lib\site-packages\matplotlib\axes\_axes.py:3491[0m, in [0;36mAxes.errorbar[1;34m(self, x, y, yerr, xerr, fmt, ecolor, elinewidth, capsize, barsabove, lolims, uplims, xlolims, xuplims, errorevery, capthick, **kwargs)[0m
[0;32m   3489[0m x, y [38;5;241m=[39m np[38;5;241m.[39matleast_1d(x, y)  [38;5;66;03m# Make sure all the args are iterable.[39;00m
[0;32m   3490[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m(x) [38;5;241m!=[39m [38;5;28mlen[39m(y):
[1;32m-> 3491[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124m'[39m[38;5;124mx[39m[38;5;124m'[39m[38;5;124m and [39m[38;5;124m'[39m[38;5;124my[39m[38;5;124m'[39m[38;5;124m must have the same size[39m[38;5;124m"[39m)
[0;32m   3493[0m everymask [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_errorevery_to_mask(x, errorevery)
[0;32m   3495[0m label [38;5;241m=[39m kwargs[38;5;241m.[39mpop([38;5;124m"[39m[38;5;124mlabel[39m[38;5;124m"[39m, [38;5;28;01mNone[39;00m)

[1;31mValueError[0m: 'x' and 'y' must have the same size
ValueError: 'x' and 'y' must have the same size

